/*
 * Copyright 2026 Yossi Eliaz
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.islo.kafka.connect.sandbox;

import java.util.Collections;
import java.util.List;
import java.util.Map;

import org.apache.kafka.common.config.AbstractConfig;
import org.apache.kafka.common.config.ConfigDef;

/** Configuration for {@link SandboxTransform}. */
public class SandboxTransformConfig extends AbstractConfig {

    public static final String RUNTIME_CONFIG = "sandbox.provider";
    private static final String RUNTIME_DOC =
        "Name of the SandboxProvider to use. Built in: \"wasm\" (in-process WebAssembly, "
            + "the default) and \"subprocess\" (an external process; no isolation, intended as a "
            + "development aid and as the latency floor for benchmarks). Additional runtimes can "
            + "be supplied by third-party JARs via ServiceLoader.";

    public static final String MODULE_CONFIG = "sandbox.module";
    private static final String MODULE_DOC =
        "Filesystem path to the .wasm module. Required by the \"wasm\" runtime.";

    public static final String COMMAND_CONFIG = "sandbox.command";
    private static final String COMMAND_DOC =
        "Command and arguments to launch. Required by the \"subprocess\", \"container\" and "
            + "\"microvm\" runtimes. Parsed as a Kafka config list, which splits on every comma "
            + "and offers no escape, so an argument that itself contains a comma cannot be "
            + "expressed here -- an inline script passed with -c is the usual way to trip over "
            + "this. Put the guest in a file, or a container image, and name it instead.";

    public static final String CALL_TIMEOUT_MS_CONFIG = "sandbox.call.timeout.ms";
    private static final String CALL_TIMEOUT_MS_DOC =
        "Maximum time to wait for the guest to transform a single record. Exceeding it fails the "
            + "task rather than stalling it indefinitely. Honoured only by the out-of-process "
            + "runtimes (\"subprocess\", \"container\", \"microvm\"), which can abandon a guest "
            + "that stops answering. The in-process \"wasm\" runtime ignores it: a wasm guest runs "
            + "on the calling task thread, and a Java thread cannot be safely killed, so there is "
            + "nothing to time out against. Bounding a guest's CPU requires a process or VM "
            + "boundary -- which is why the runtime is pluggable.";

    public static final String SCHEMAS_ENABLE_CONFIG = "schemas.enable";
    private static final String SCHEMAS_ENABLE_DOC =
        "Whether the record envelope carries Connect schemas. Passed through to the internal "
            + "JsonConverter, so the wire format matches Connect's canonical JSON mapping.";

    public static final String MAX_MEMORY_PAGES_CONFIG = "sandbox.wasm.max.memory.pages";
    private static final String MAX_MEMORY_PAGES_DOC =
        "Upper bound on the guest's linear memory, in 64KiB WebAssembly pages. The guest cannot "
            + "grow beyond this, which bounds the blast radius of a memory-hungry transform.";

    public static final String COMPILE_CONFIG = "sandbox.wasm.compile";
    private static final String COMPILE_DOC =
        "Compile the wasm module to JVM bytecode when the task starts, instead of interpreting "
            + "it. Costs a few milliseconds once and is dramatically faster per record for any "
            + "guest that does real work. Isolation is unchanged: the generated bytecode still "
            + "enforces WebAssembly's memory bounds and has no host imports to call.";

    public static final String DOCKER_HOST_CONFIG = "sandbox.docker.host";
    private static final String DOCKER_HOST_DOC =
        "Docker Engine endpoint. The microvm provider defaults to Docker Sandboxes' engine at "
            + "~/.sbx/run/d/docker.sock; the container provider defaults to the ambient socket.";

    public static final String DOCKER_IMAGE_CONFIG = "sandbox.docker.image";
    private static final String DOCKER_IMAGE_DOC = "Image the guest runs in.";

    public static final String DOCKER_NAME_CONFIG = "sandbox.docker.name";
    private static final String DOCKER_NAME_DOC =
        "Sandbox name. Defaults to a unique name per task so parallel tasks never collide.";

    public static final String DOCKER_CPUS_CONFIG = "sandbox.docker.cpus";
    private static final String DOCKER_CPUS_DOC =
        "CPUs allocated to the sandbox. This is the bound the wasm provider cannot offer.";

    public static final String DOCKER_MEMORY_CONFIG = "sandbox.docker.memory";
    private static final String DOCKER_MEMORY_DOC = "Memory limit (e.g. 512m, 2g).";

    public SandboxTransformConfig(final Map<String, ?> originals) {
        super(config(), originals);
    }

    public static ConfigDef config() {
        return new ConfigDef()
            .define(RUNTIME_CONFIG, ConfigDef.Type.STRING, "wasm",
                ConfigDef.Importance.HIGH, RUNTIME_DOC)
            .define(MODULE_CONFIG, ConfigDef.Type.STRING, "",
                ConfigDef.Importance.HIGH, MODULE_DOC)
            .define(COMMAND_CONFIG, ConfigDef.Type.LIST, Collections.emptyList(),
                ConfigDef.Importance.HIGH, COMMAND_DOC)
            .define(CALL_TIMEOUT_MS_CONFIG, ConfigDef.Type.LONG, 1000L,
                ConfigDef.Range.atLeast(1L), ConfigDef.Importance.MEDIUM, CALL_TIMEOUT_MS_DOC)
            .define(SCHEMAS_ENABLE_CONFIG, ConfigDef.Type.BOOLEAN, true,
                ConfigDef.Importance.MEDIUM, SCHEMAS_ENABLE_DOC)
            .define(MAX_MEMORY_PAGES_CONFIG, ConfigDef.Type.INT, 64,
                ConfigDef.Range.between(1, 32767), ConfigDef.Importance.MEDIUM,
                MAX_MEMORY_PAGES_DOC)
            .define(COMPILE_CONFIG, ConfigDef.Type.BOOLEAN, true,
                ConfigDef.Importance.MEDIUM, COMPILE_DOC)
            .define(DOCKER_HOST_CONFIG, ConfigDef.Type.STRING, "",
                ConfigDef.Importance.MEDIUM, DOCKER_HOST_DOC)
            .define(DOCKER_IMAGE_CONFIG, ConfigDef.Type.STRING, "",
                ConfigDef.Importance.HIGH, DOCKER_IMAGE_DOC)
            .define(DOCKER_NAME_CONFIG, ConfigDef.Type.STRING, "",
                ConfigDef.Importance.LOW, DOCKER_NAME_DOC)
            .define(DOCKER_CPUS_CONFIG, ConfigDef.Type.STRING, "1",
                ConfigDef.Importance.MEDIUM, DOCKER_CPUS_DOC)
            .define(DOCKER_MEMORY_CONFIG, ConfigDef.Type.STRING, "512m",
                ConfigDef.Importance.MEDIUM, DOCKER_MEMORY_DOC);
    }

    public String providerName() {
        return getString(RUNTIME_CONFIG);
    }

    public String module() {
        return getString(MODULE_CONFIG);
    }

    public List<String> command() {
        return getList(COMMAND_CONFIG);
    }

    public long callTimeoutMs() {
        return getLong(CALL_TIMEOUT_MS_CONFIG);
    }

    public boolean schemasEnable() {
        return getBoolean(SCHEMAS_ENABLE_CONFIG);
    }

    public int maxMemoryPages() {
        return getInt(MAX_MEMORY_PAGES_CONFIG);
    }

    public boolean compile() {
        return getBoolean(COMPILE_CONFIG);
    }

    public String dockerHost() {
        return getString(DOCKER_HOST_CONFIG);
    }

    public String dockerImage() {
        return getString(DOCKER_IMAGE_CONFIG);
    }

    public String dockerName() {
        final String configured = getString(DOCKER_NAME_CONFIG);
        return configured.isEmpty()
            ? "connect-sandbox-" + java.util.UUID.randomUUID() : configured;
    }

    public String dockerCpus() {
        return getString(DOCKER_CPUS_CONFIG);
    }

    public String dockerMemory() {
        return getString(DOCKER_MEMORY_CONFIG);
    }
}
