rootLogger.level = WARN
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1} - %m%n
rootLogger.appenderRef.stdout.ref = STDOUT
logger.sandbox.name = dev.islo.kafka.connect.sandbox
logger.sandbox.level = INFO
